cinnamon:
  clusters:
    - name: prod
      properties:
        bootstrap.servers: kafka-prod:9094
    - name: dev
      properties:
        bootstrap.servers: kafka-dev:29094
  schema-registries:
    - name: prod
      schema.registry.url: http://schema-registry-prod:8081
    - name: dev
      schema.registry.url: http://schema-registry-dev:8081
  cli_templates:
    - kcat -b {{bootstrap}} -t {{topic}} -o beginning -f '{"Key":"%k","Value":%s,"Timestamp":%T,"Partition":%p,"Offset":%o,"Headers":"%h","Size":%S}\n' -u | jq .
    - kcat -b {{bootstrap}} -t {{topic}}

